### ISSUE TITLE
Error when loading bark skill

### ISSUE THREAD

**Issue by devvmh** [jmillerv/mycroft2-skills#8]
Hey, thanks for setting up this repo. I tried installing the bark skill but I got an error

```
n 12 03:39:35 localhost.localdomain python[4582]: DEBUG:skills:Loading skill bark.mark2
Jan 12 03:39:35 localhost.localdomain python[4582]: ERROR:skills:Failed to load skill: bark.mark2 (NameError("name 'MycroftSkill' is not defined"))
Jan 12 03:39:35 localhost.localdomain python[4582]: Traceback (most recent call last):
Jan 12 03:39:35 localhost.localdomain python[4582]:   File "/opt/mycroft-dinkum/services/skills/service/load.py", line 61, in load_skill_source
Jan 12 03:39:35 localhost.localdomain python[4582]:     skill_module = _load_skill_module(main_file_path, skill_id)
Jan 12 03:39:35 localhost.localdomain python[4582]:   File "/opt/mycroft-dinkum/services/skills/service/load.py", line 88, in _load_skill_module
Jan 12 03:39:35 localhost.localdomain python[4582]:     spec.loader.exec_module(mod)
Jan 12 03:39:35 localhost.localdomain python[4582]:   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
Jan 12 03:39:35 localhost.localdomain python[4582]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jan 12 03:39:35 localhost.localdomain python[4582]:   File "/opt/mycroft-dinkum/skills/bark.mark2/__init__.py", line 1, in <module>
Jan 12 03:39:35 localhost.localdomain python[4582]:     class Bark(MycroftSkill):
Jan 12 03:39:35 localhost.localdomain python[4582]: NameError: name 'MycroftSkill' is not defined
Jan 12 03:39:35 localhost.localdomain python[4582]: ERROR:skills:Service failed to start
Jan 12 03:39:35 localhost.localdomain python[4582]: Traceback (most recent call last):
Jan 12 03:39:35 localhost.localdomain python[4582]:   File "/opt/mycroft-dinkum/shared/mycroft/service/dinkum_service.py", line 65, in main
Jan 12 03:39:35 localhost.localdomain python[4582]:     self.start()
Jan 12 03:39:35 localhost.localdomain python[4582]:   File "/opt/mycroft-dinkum/services/skills/service/__main__.py", line 43, in start
Jan 12 03:39:35 localhost.localdomain python[4582]:     self._load_skills()
Jan 12 03:39:35 localhost.localdomain python[4582]:   File "/opt/mycroft-dinkum/services/skills/service/__main__.py", line 68, in _load_skills
Jan 12 03:39:35 localhost.localdomain python[4582]:     assert (
Jan 12 03:39:35 localhost.localdomain python[4582]: AssertionError: Failed to load skill module from /opt/mycroft-dinkum/skills/bark.mark2
```

Any ideas what might be going wrong?

I'm thinking of converting or creating some new skills for Dinkum/core so using this as a starting point / sanity check. Thanks!

**Comment by devvmh** [comment]
```
diff --git a/bark.mark2/__init__.py b/bark.mark2/__init__.py
index 806597b..99ae782 100644
--- a/bark.mark2/__init__.py
+++ b/bark.mark2/__init__.py
@@ -1,8 +1,13 @@
+from mycroft.skills import (
+    MycroftSkill,
+    intent_handler
+)
+
 class Bark(MycroftSkill):
     def __init__(self, skill_id: str):
         super().__init__(skill_id=skill_id, name="BarkSkill")

-    @intent_file_handler('bark.intent')
+    @intent_handler('bark.intent')
     def handle_bark(self, message):
         dialog="bark"
         gui = None
```

works

**Comment by devvmh** [comment]
should be fixed by https://github.com/jmillerv/mycroft2-skills/pull/9
